### ISSUE TITLE
Clarification on capitalization in install instructions

### ISSUE THREAD

**Issue by bangpound** [creof/doctrine2-spatial#10]
I am using this bundle successfully, but it took me (a new Symfony2 developer) several hours to sort out why I could update my doctrine's database schema but it would always fail validation.

The problem seems to have been related to the capitalization of the geometry type in the DB column comment: `(DC2Type:Point)` or `(DC2Type:Polygon)`.

Originally, I had used lowercase data type names throughout (except for the names of classes). I could get the schema to validate (after successfully updating it without a problem) only after changing the case of the comment: `(DC2Type:Polygon)` became `(DC2Type:polygon)`.

Now I've gotten closer to a more reliable fix... capitalization throughout.

``` yaml
        types:
            Geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            Point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            Polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            LineString: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
        mapping_types:
            geometry: Geometry
            point: Point
            polygon: Polygon
            linestring: LineString
```

I have defined my columns in PHP annotations like this:

``` php

    /**
     * @var Point
     *
     * @ORM\Column(name="coordinates", type="Point", nullable=true)
     */
    private $coordinates;

    /**
     * @var Polygon
     *
     * @ORM\Column(name="bounding_box", type="Polygon", nullable=true)
     */
    private $boundingBox;
```

I don't really understand what I was doing wrong: why the types had to be capitalized when normally they can be lowercase? This fix also contradicts and expands on the installation instructions. If someone can get to the bottom of my mistake, I'd happily make a pull request that improves the installation instructions (at least for MySQL).
