### ISSUE TITLE
“Unknown database type point requested” on schema update

### ISSUE THREAD

**Issue by jaikdean** [creof/doctrine2-spatial#176]
I have the following setup in a Symfony 3.3 app:

```yml
# config.yml
doctrine:
    dbal:
        types:
            geography_point: CrEOF\Spatial\DBAL\Types\Geography\PointType
```

```php
class Outlet
{
    /**
     * @var CrEOF\Spatial\PHP\Types\Geography\Point
     * @ORM\Column(name="location", type="geography_point", nullable=true)
     */
    private $location;
}
```

This works as expected, creating the following table:

```sql
CREATE TABLE `outlet` (
  `location` point DEFAULT NULL COMMENT '(DC2Type:geography_point)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

However, when I run a `php bin/console doctrine:schema:update` I get the following exception:

```
[Doctrine\DBAL\DBALException]                                                                     
Unknown database type point requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

Any ideas what to try?

**Comment by mikysan** [comment]
run into same problem!

**Comment by kmusiclife** [comment]
same problem I detected.

**Comment by braianj** [comment]
same here. Any news?

**Comment by alejandrososa** [comment]
It´s work for me `doctrine:
    dbal:
        types:
            point:  CommonBundle\Type\PointType
        default_connection: app
        connections:
            app:
                driver: pdo_mysql
                host:   '%database_host%'
                port:   '%database_port%'
                dbname: '%database_name%'
                user:   '%database_user%'
                password: '%database_password%'
                charset: UTF8
                mapping_types:
                    enum: string
                    set: string
                    point: point`

**Comment by jsampedro77** [comment]
As @alejandrososa sated, I had to declare  the mapping type to get rid of this problem

```
doctrine:
    dbal:
        mapping_types:
            point: point
```

**Comment by alexislefebvre** [comment]
We have the same problem with Symfony 4.1.1 and doctrine/orm 2.6.1

We installed this bundle in order to use the `CrEOF\Spatial\DBAL\Types\Geography\PointType` type.

But generating Doctrine migration triggered the following error:

> Unknown database type geometry requested, Doctrine\DBAL\Platforms\PostgreSQL94Platform may not support it.

We has similar errors and we had to declare other types:

```yaml
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '9.4'

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            geography:  CrEOF\Spatial\DBAL\Types\GeographyType
        mapping_types:
            _text: string
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            # …
        dql:
            numeric_functions:
                point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
```

And it returns a strange error:

``` bash
$ bin/console doctrine:schema:update --dump-sql

In AbstractPostgreSQLDriver.php line 99:
                                                                                                                                                                                                          
  An exception occurred while executing 'SELECT quote_ident(r.conname) as conname, pg_catalog.pg_get_constraintdef(r.oid, true) as condef                                                                 
                    FROM pg_catalog.pg_constraint r                                                                                                                                                       
                    WHERE r.conrelid =                                                                                                                                                                    
                    (                                                                                                                                                                                     
                        SELECT c.oid                                                                                                                                                                      
                        FROM pg_catalog.pg_class c, pg_catalog.pg_namespace n                                                                                                                             
                        WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'state' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',us  
  er),' ','') from pg_catalog.pg_settings where name = 'search_path'),',')) AND n.oid = c.relnamespace                                                                                                    
                    )                                                                                                                                                                                     
                    AND r.contype = 'f'':                                                                                                                                                                 
                                                                                                                                                                                                          
  SQLSTATE[21000]: Cardinality violation: 7 ERROR:  more than one row returned by a subquery used as an expression                                                                                        
                                                                                                                                                                                                          

In PDOConnection.php line 109:
                                                                                                                    
  SQLSTATE[21000]: Cardinality violation: 7 ERROR:  more than one row returned by a subquery used as an expression  
                                                                                                                    

In PDOConnection.php line 107:
                                                                                                                    
  SQLSTATE[21000]: Cardinality violation: 7 ERROR:  more than one row returned by a subquery used as an expression  
```
