### ISSUE TITLE
Error in documentation for configuration Symfony

### ISSUE THREAD

**Issue by Ferrer-Jeremy** [creof/doctrine2-spatial#181]
On [this page](https://github.com/creof/doctrine2-spatial/blob/master/doc/configuration.md)
The config is:
```yml
doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        dql:
            numeric_functions:
                st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Area
                st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                st_intersects:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                st_buffer:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STBuffer
                point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
``` 

And should be:
```yml
doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

    orm:
        entity_managers:
            default:
                dql:
                    numeric_functions:
                        st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                        contains:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                        st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Area
                        st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                        st_intersects:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                        st_buffer:     CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STBuffer
                        point: CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
``` 

Source: [Doc Symfony](https://symfony.com/doc/current/reference/configuration/doctrine.html)
