### ISSUE TITLE
Doctrine repeatly creates geometry-type field

### ISSUE THREAD

**Issue by forsetius** [creof/doctrine2-spatial#182]
Having configured the bundle:
```yaml
doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            geography:   CrEOF\Spatial\DBAL\Types\GeographyType
```

in entity class I defined a field:
```php
    /**
     * @ORM\Column(type="geography", nullable=true)
     */
    protected $geomshape;
```

then executed `bin/console doctrine:generate:entities...` and `bin/console doctrine:schema:update`.
Now in the Postgres DB I have a new `geomshape` field of `geography` type but it's comment is `DC2Type:geometry`. 

Problem is that on the next time I use `bin/console doctrine:schema:update` it wants to alter `geomshape` field to type `Geography` again: 
```sql
ALTER TABLE geo_objects ALTER geomshape TYPE Geography;
```
And again, every time I use `d:s:u`. Is this my fault (perhaps misconfiguration) or a bug?
